### ISSUE TITLE
Player is rideable by every entity

### ISSUE THREAD

**Issue by JulianKalmbach** [LotsOfPixelsStudios/Monstera#74]
**Describe the bug**
If the player behavior is touched, the vanilla player behavior gets created automatically, so the developer doesn't have to care about that. The rideable component there is missing the part that filters the familiy types that are able to ride the player. Therefore every entity will be pulled in by the player.

**Version**
Monstera: 0.0.4-SNAPSHOT21

**To Reproduce**
- Do anything at the player behavior (add a property or whatever)
- Build and see the error in the rideable component.
```json
"minecraft:rideable": {
  "seat_count": 2,
  "pull_in_entities": true,
  "seats": [
    {
      "position": [
        0.4,
        -0.2,
        -0.1
      ],
      "min_rider_count": 0,
      "max_rider_count": 0,
      "lock_rider_rotation": 0
    },
    {
      "position": [
        -0.4,
        -0.2,
        -0.1
      ],
      "min_rider_count": 1,
      "max_rider_count": 2,
      "lock_rider_rotation": 0
    }
  ]
}
```

**Expected behavior**
The rideable component needs to contain the family types that are allowed to ride the player:
```json
"minecraft:rideable": {
  "seat_count": 2,
  "family_types": [
    "parrot_tame"
  ],
  "pull_in_entities": true,
  "seats": [
    {
      "position": [ 0.4, -0.2, -0.1 ],
      "min_rider_count": 0,
      "max_rider_count": 0,
      "lock_rider_rotation": 0
    },
    {
      "position": [ -0.4, -0.2, -0.1 ],
      "min_rider_count": 1,
      "max_rider_count": 2,
      "lock_rider_rotation": 0
    }
  ]
}
```

**Comment by 12rcu** [comment]
this is a [std lib](https://git.timoliacreative.de/technologies/tranclate-std-lib/-/blob/master/src/main/kotlin/com/tcreative/devtools/stdlib/player/beh/PlayerBehComponents.kt?ref_type=heads#L160) issue. 
```kotlin
familyTypes = arrayListOf("parrot_tame")
```
needs to be 
```kotlin
familyTypes("parrot_tame")
```

**Comment by JulianKalmbach** [comment]
Ah, true.
Forgot that player modifications are part of the std-lib
